function EmployeeProfile({ employee, profilePanels, toggleProfilePanel, setProfilePanels, profilePanelFields, profileWorkTab, setProfileWorkTab, onEditProfile, onEditSection, onAddEducation, onDeleteEducation, formatProfileDate }) {
    const qid = String(employee.employee_id || "").replace(/^EMP/i, "").padStart(3, "0");

    return (
        <section className="employee-profile-view">
            <div className="employee-profile-topbar"><span>Employee Overview</span><button type="button" onClick={() => { const shouldOpen = Object.values(profilePanels).every((open) => !open); setProfilePanels(Object.fromEntries(Object.keys(profilePanels).map((key) => [key, shouldOpen]))); }} aria-label="Expand or collapse all profile sections">{Object.values(profilePanels).some(Boolean) ? "⌃" : "⌄"}</button></div>
            <div className="employee-section-heading"><div><h2>My Profile</h2><p>Complete employee information from HR records</p></div></div>
            <aside className="profile-summary-card">
                <div className="profile-summary-cover" />
                <div className="profile-summary-avatar">{employee.profile_photo ? <img src={employee.profile_photo} alt={employee.name} /> : employee.name?.charAt(0)?.toUpperCase()}</div>
                <h2>{employee.name}</h2>
                <span className="profile-summary-status">● {employee.status || "Active"}</span>
                <div className="profile-summary-tags"><span>{employee.designation || "Employee"}</span><span>{employee.employment_type || "Full time"}</span></div>
                <div className="profile-summary-actions"><button type="button" onClick={onEditProfile}>✎ Edit Info</button><a href={`mailto:${employee.email}`}>▣ Message</a></div>
                <div className="profile-summary-info-section profile-summary-basic-information"><h3>Basic information</h3>
                    <div><span>Phone</span><strong>{employee.phone || "-"}</strong></div>
                    <div><span>QID</span><strong>{qid === "000" ? "-" : qid}</strong></div>
                    <div><span>Email</span><strong>{employee.email || "-"}</strong></div>
                    <div><span>Gender</span><strong>{employee.gender || "-"}</strong></div>
                    <div><span>Birthday</span><strong>{formatProfileDate(employee.date_of_birth)}</strong></div>
                    <div><span>Joining Date</span><strong>{formatProfileDate(employee.joining_date)}</strong></div>
                    <div><span>Employment Type</span><strong>{employee.employment_type || "-"}</strong></div>
                    <div><span>Address</span><strong>{employee.address || "-"}</strong></div>
                </div>
                <div className="profile-summary-info-section"><h3>Personal Information</h3><div><span>Nationality</span><strong>{employee.nationality || employee.country || "-"}</strong></div><div><span>Religion</span><strong>{employee.religion || "-"}</strong></div><div><span>Marital status</span><strong>{employee.marital_status || "-"}</strong></div><div><span>No. of children</span><strong>{employee.children_count ?? "-"}</strong></div></div>
                <div className="profile-summary-info-section profile-summary-emergency"><h3>Emergency Contact Number</h3><div><span>Primary</span><strong>{employee.emergency_contact || "-"}</strong></div></div>
            </aside>
            <div className="dashboard-profile-panels">
                <DashboardProfilePanel title="About Employee" open={profilePanels.about} onToggle={() => toggleProfilePanel("about")} onEdit={() => onEditSection("about")} content={<p>{employee.about || `Employee ${employee.name} is part of the ${employee.department || "organization"} team as a ${employee.designation || "valued employee"}.`}</p>} />
                <DashboardProfilePanel title="Bank Information" open={profilePanels.bank} onToggle={() => toggleProfilePanel("bank")} onEdit={() => onEditSection("bank")} content={<div className="dashboard-profile-grid">{profilePanelFields([["Account Holder", employee.bank?.account_holder_name], ["Bank Name", employee.bank?.bank_name], ["Account Number", employee.bank?.account_number], ["Branch Name", employee.bank?.branch_name], ["IFSC Code", employee.bank?.ifsc_code], ["Account Type", employee.bank?.account_type]])}</div>} />
                <DashboardProfilePanel title="Family Information" open={profilePanels.family} onToggle={() => toggleProfilePanel("family")} onEdit={() => onEditSection("family")} content={<div className="dashboard-profile-grid">{profilePanelFields([["Father Name", employee.family?.father_name], ["Mother Name", employee.family?.mother_name], ["Spouse Name", employee.family?.spouse_name], ["Spouse Employment", employee.family?.spouse_employment], ["Marital Status", employee.marital_status], ["Children", employee.children_count]])}</div>} />
                <DashboardProfilePanel title="Employment Details" open={profilePanels.employment} onToggle={() => toggleProfilePanel("employment")} onEdit={() => onEditSection("employment")} content={<div className="dashboard-profile-grid">{profilePanelFields([["Legal Entity", employee.legal_entity || "SHLT"], ["Worker Type", employee.worker_type || "Employee"], ["Personnel Number", employee.employee_id], ["Employment Category", employee.employment_category], ["Employment Start", formatProfileDate(employee.joining_date)], ["Employment End", employee.employment_end_date || "Never"], ["Employment Type", employee.employment_type], ["Project Role ID", employee.project_role_id], ["Termination Reason", employee.termination_reason], ["Last Date Worked", employee.last_date_worked]])}</div>} />
                <DashboardProfilePanel title="Position Details" open={profilePanels.position} onToggle={() => toggleProfilePanel("position")} onEdit={() => onEditSection("position")} content={<div className="dashboard-profile-grid">{profilePanelFields([["Position", employee.position || employee.designation], ["Position Title", employee.position_title || employee.designation], ["Assignment Start", formatProfileDate(employee.assignment_start || employee.joining_date)], ["Assignment End", formatProfileDate(employee.assignment_end)], ["Make Primary", employee.make_primary ? "Yes" : "No"]])}</div>} />
                <div className="dashboard-profile-panel-row"><DashboardProfilePanel title="Education Details" open={profilePanels.education} onToggle={() => toggleProfilePanel("education")} onEdit={() => onEditSection("education")} content={<div className="education-records">{(Array.isArray(employee.education) ? employee.education : []).map((education) => <article className="education-record" key={education.id}><div><strong>{education.qualification || "Qualification"}{education.specialization ? ` ${education.specialization}` : ""}</strong><span>{education.institution || "-"}</span><small>{education.start_year || "-"} - {education.currently_pursuing ? "Present" : education.end_year || "-"} {education.grade ? `• ${education.grade}` : ""}</small></div><div><button type="button" onClick={() => onEditSection("education", education.id)}>Edit</button><button type="button" onClick={() => onDeleteEducation(education.id)}>Delete</button></div></article>)}<button type="button" className="add-education-button" onClick={onAddEducation}>+ Add Education</button></div>} /><DashboardProfilePanel title="Experience" open={profilePanels.experience} onToggle={() => toggleProfilePanel("experience")} onEdit={() => onEditSection("experience")} content={<div className="dashboard-profile-grid">{profilePanelFields([["Company", employee.experience?.company_name], ["Role", employee.experience?.designation], ["Start", formatProfileDate(employee.experience?.start_date)], ["End", formatProfileDate(employee.experience?.end_date)]])}</div>} /></div>
                <section className="dashboard-projects-panel"><div className="dashboard-project-tabs"><button className={profileWorkTab === "projects" ? "active" : ""} onClick={() => setProfileWorkTab("projects")}>Projects</button><button className={profileWorkTab === "assets" ? "active" : ""} onClick={() => setProfileWorkTab("assets")}>Assets</button></div>{profileWorkTab === "projects" ? <div className="dashboard-project-list"><article><span className="dashboard-project-icon blue">C</span><div><b>{employee.department || "Workforce"} Management</b><p>Employee responsibilities and assigned work</p></div></article><article><span className="dashboard-project-icon purple">●</span><div><b>{employee.designation || "Employee"} Operations</b><p>Current role and organizational activities</p></div></article></div> : <div className="dashboard-assets-empty">No assets assigned</div>}</section>
            </div>
        </section>
    );
}

function DashboardProfilePanel({ title, open, onToggle, onEdit, content }) {
    return <section className={`dashboard-profile-panel ${open ? "open" : "collapsed"}`}><header><h3>{title}</h3>{onEdit && <button type="button" className="dashboard-profile-edit-button" onClick={onEdit} aria-label={`Edit ${title}`}>✎</button>}<button type="button" className="dashboard-profile-toggle-button" onClick={onToggle} aria-label={`${open ? "Collapse" : "Expand"} ${title}`}>{open ? "⌃" : "⌄"}</button></header>{open && <div className="dashboard-profile-panel-content">{content}</div>}</section>;
}

export default EmployeeProfile;
